

const MAPPING = {
    rock: {
        rock: 0,
        fire: 1,
        scissor: 1,
        snake: 1,
        human: 1,
        tree: 1, 
        wolf: 1, 
        sponge: 1,
        paper: -1,
        air: -1,
        water: -1,
        dragon: -1,
        devil: -1,
        lightning: -1,
        gun: -1
    },
    fire: {
        fire: 0,
        scissor: 1,
        snake: 1,
        human: 1,
        tree: 1, 
        wolf: 1, 
        sponge: 1,
        paper: 1,
        air: -1,
        water: -1,
        dragon: -1,
        devil: -1,
        lightning: -1,
        gun: -1,
        rock: -1
    },
    scissor: {
        scissor: 0,
        snake: 1,
        human: 1,
        tree: 1, 
        wolf: 1, 
        sponge: 1,
        paper: 1,
        air: 1,
        water: -1,
        dragon: -1,
        devil: -1,
        lightning: -1,
        gun: -1,
        rock: -1,
        fire: -1
    },
    snake: {
        snake: 0,
        human: 1,
        tree: 1, 
        wolf: 1, 
        sponge: 1,
        paper: 1,
        air: 1,
        water: 1,
        dragon: -1,
        devil: -1,
        lightning: -1,
        gun: -1,
        rock: -1,
        fire: -1,
        scissor: -1
    },
    human: {
        human: 0,
        tree: 1, 
        wolf: 1, 
        sponge: 1,
        paper: 1,
        air: 1,
        water: 1,
        dragon: 1,
        devil: -1,
        lightning: -1,
        gun: -1,
        rock: -1,
        fire: -1,
        scissor: -1,
        snake: -1
    },
    tree:{
        tree: 0, 
        wolf: 1, 
        sponge: 1,
        paper: 1,
        air: 1,
        water: 1,
        dragon: 1,
        devil: 1,
        lightning: -1,
        gun: -1,
        rock: -1,
        fire: -1,
        scissor: -1,
        snake: -1,
        human:-1
    },
    wolf:{ 
        wolf: 0, 
        sponge: 1,
        paper: 1,
        air: 1,
        water: 1,
        dragon: 1,
        devil: 1,
        lightning: 1,
        gun: -1,
        rock: -1,
        fire: -1,
        scissor: -1,
        snake: -1,
        human:-1,
        tree: -1
    },
    sponge:{
        sponge: 0,
        paper: 1,
        air: 1,
        water: 1,
        dragon: 1,
        devil: 1,
        lightning: 1,
        gun: 1,
        rock: -1,
        fire: -1,
        scissor: -1,
        snake: -1,
        human:-1,
        tree: -1,
        wolf: -1
    },
    paper: {
        paper: 0,
        air: 1,
        water: 1,
        dragon: 1,
        devil: 1,
        lightning: 1,
        gun: 1,
        rock: 1,
        fire: -1,
        scissor: -1,
        snake: -1,
        human:-1,
        tree: -1,
        wolf: -1,
        sponge: -1
    },
    air:{
        air: 0,
        water: 1,
        dragon: 1,
        devil: 1,
        lightning: 1,
        gun: 1,
        rock: 1,
        fire: 1,
        scissor: -1,
        snake: -1,
        human:-1,
        tree: -1,
        wolf: -1,
        sponge: -1,
        paper: -1
    },
    water:{
        water: 0,
        dragon: 1,
        devil: 1,
        lightning: 1,
        gun: 1,
        rock: 1,
        fire: 1,
        scissor: 1,
        snake: -1,
        human:-1,
        tree: -1,
        wolf: -1,
        sponge: -1,
        paper: -1,
        air: -1
    },
    dragon:{
        dragon:0,
        devil: 1,
        lightning: 1,
        gun: 1,
        rock: 1,
        fire: 1,
        scissor: 1,
        snake: 1,
        human:-1,
        tree: -1,
        wolf: -1,
        sponge: -1,
        paper: -1,
        air: -1,
        water: -1
    },
    devil:{
        devil: 0,
        lightning: 1,
        gun: 1,
        rock: 1,
        fire: 1,
        scissor: 1,
        snake: 1,
        human: 1,
        tree: -1,
        wolf: -1,
        sponge: -1,
        paper: -1,
        water: -1,
        air: -1,
        dragon: -1,
    },
    lightning:{
        lightning: 0,
        gun: 1,
        rock: 1,
        fire: 1,
        scissor: 1,
        snake: 1,
        human: 1,
        tree: 1,
        wolf: -1,
        sponge: -1,
        paper: -1,
        air: -1,
        water: -1,
        dragon: -1,
        devil: -1
    },
    gun: {
        gun:0,
        rock: 1,
        fire: 1,
        scissor: 1,
        snake: 1,
        human: 1,
        tree: 1,
        wolf: 1,
        sponge: -1,
        paper: -1,
        air: -1,
        water: -1,
        dragon: -1,
        devil: -1,
        lightning: -1
    }

};

module.exports = MAPPING;